### ISSUE TITLE
add storybook skeleton sample - youtube card

### ISSUE THREAD

**Issue by imagine10255** [acrool/acrool-react-skeleton#1]
add storybook skeleton sample

The purpose is to select the closest one, copy and paste it when needed, and then make minimal modifications to achieve the target style.

**Comment by imagine10255** [comment]
Uploading CleanShot 2024-10-07 at 16.05.41.mp4…

**Comment by nickychen00** [comment]
TableCard skeleton example

Link: https://bootstrap-vue.org/docs/components/skeleton

![image](https://github.com/user-attachments/assets/96cc4e33-12ed-455d-8166-bae9de2220f1)
